config/routes.rb
G4up::Application.routes.draw do
  get "replies/new" # TODO いらないはずなので確認してから消す

  match 'pages/:page' => 'entries#index'
  root to: 'entries#index'
  resources :entries do
    member do
      get 'full(/*filename)' => 'entries#full', as: :full
      get :full # 後方互換
    end
    collection { get :search }
    resources :replies, as: :entries
    resources :complaints
  end
  resources :tags, as: :acts_as_taggable_on_tags

  match 'feed/atom' => 'feed#atom', format: 'xml'

end

app/models/entry.rb
# -*- encoding: UTF-8 -*-
class Entry < ActiveRecord::Base
  belongs_to :parent, class_name: 'Entry', counter_cache: :replies_count
  has_many :replies, class_name: 'Entry', foreign_key: :parent_id
  has_many :complaints, dependent: :delete_all
  has_attached_file(:photo, {
    styles: {thumb: '320x180'},
    use_timestamp: false,
    url: '/system/:attachment/:id/:style/g4u:id.:extension',
    storage: :filesystem,
    path: ':rails_root/public:url',
  })
  acts_as_taggable
  paginates_per 48

  attr_writer :other_tags
  attr_accessible :photo, :body, :tag_list, :other_tags

  scope :recent, order("#{quoted_table_name}.created_at desc")
  scope :root, where(parent_id: nil)
  scope :date_from, lambda{|time|
    time = Time.zone.parse(time) if time.is_a?(String)
    where(["#{quoted_table_name}.created_at >= ?", time])
  }
  scope :date_to, lambda{|time|
    time = Time.zone.parse(time) if time.is_a?(String)
    where(["#{quoted_table_name}.created_at <= ?", time.end_of_day])
  }

  validates :body, length: {maximum: 140}
  validates :photo, presence: {unless: :parent}
  validates_each :photo do |record, attr, photo|
    photo.queued_for_write[:original] or next
    dimensions = Paperclip::Geometry.from_file(photo.queued_for_write[:original])
    unless dimensions.width == 1280 && dimensions.height == 720
      record.errors.add(attr, 'のサイズは 1280x720 にしてください。')
    end
  end
  validates :photo_file_name, presence: {unless: :parent}
  validates_attachment_size :photo, :less_than => 600.kilobytes, message: 'は 600KB 以下にしてください。'
  validates :photo_fingerprint, uniqueness: true

  before_validation :add_tag_from_filename
  before_validation :add_other_tags

  def censor!
    update_attribute(:censored, true)
  end

  def root?
    parent_id.blank?
  end

  def filename
    photo.blank? and return nil
    File.basename(photo.path)
  end

  def change_storage(new_storage)
    old_storage = self.storage
    old_pathes = photo.styles.keys.map{|x|photo.path(x)} + [photo.path]
    file = photo.to_file
    update_attribute(:storage, new_storage)
    new_record = self.class.find(self.id)
    new_record.photo = file
    new_record.save
    if old_storage == 'filesystem'
      old_pathes.each do |path|
        File.unlink(path)
      end
    end
  end

  def idol
    Idol.all.detect{|x|self.tag_list.include?(x.name)}
  end

  class << self
    # 古いのを s3 に移す
    def archive(new_storage='s3', offset=1000)
      entries = where("photo_filename <> ''").
                where(storage: 'filesystem').
                order('id desc').offset(offset)
      entries.each do |entry|
        logger.debug('change_storage: %d, %s' % [entry.id, entry.photo.path])
        entry.change_storage(new_storage)
      end
    end
  end

  def other_tags
    @other_tags ||
      tag_list.reject{|x| Idol.names.include?(x)}.join(' ')
  end

  private

  def photo_blank?
    photo_file_name.blank?
  end

  def body_blank?
    body.blank?
  end

  # ファイル名にアイドルの名前が含まれていたらタグに追加
  def add_tag_from_filename
    photo.original_filename.present? or return
    names = Idol.names.sort_by(&:length).reverse
    tag = names.detect{|n| photo.original_filename.include?(n)}
    self.tag_list << tag if tag
  end

  def add_other_tags
    ts = other_tags.to_s.strip.split(/\s+/)
    tag_list.concat(ts) if ts.present?
  end

end

app/controllers/entries_controller.rb
# -*- encoding: UTF-8 -*-
class EntriesController < ApplicationController
  respond_to :html, :json, :js
  include ApplicationHelper

  caches_page :index, :if=>lambda{|c| c.params[:page].nil? }
  cache_sweeper :entry_sweeper

  def index
    @entries = Entry.root.recent.includes(:tags).page(params[:page])
    # tag cloud
    @tags = Entry.tag_counts_on(:tags).order('count desc').limit(13)
  end

  def show
    @entry = Entry.find(params[:id])
    @replies = @entry.replies.recent.page(params[:page])
    @reply = @entry.replies.new
    respond_with @entry
  end

  def full
    # 画像にリダイレクト
    @entry = Entry.find(params[:id])
    redirect_to @entry.photo.url(:original)
  end

  def new
    @entry = Entry.new()
  end

  def create
    @entry = Entry.new(params[:entry])
    unless @entry.save()
      render action: :new and return
    end
    redirect_to :root
  end

  def edit
    @entry = Entry.root.find(params[:id])
  end

  def update
    @entry = Entry.root.find(params[:id])
    @entry.attributes = params[:entry].slice(:tag_list, :other_tags)
    @entry.save()
    redirect_to entry_full_url(@entry)
  end

  def search
    entries = Entry.root.recent.includes(:tags).page(params[:page])
    begin
      entries = entries.date_from(params[:from]) if params[:from].present?
      entries = entries.date_to(params[:to]) if params[:to].present?
    rescue ArgumentError
      #flash[:error] = '日付がおかしい'
    end
    entries = entries.tagged_with(params[:tag]) if params[:tag].present?
    @entries = entries
    render :index
  end

  private

  def _2ch_viewer?
    ua = request.headers['User-Agent']
    %w(BB2C Monazilla).any?{|name| ua.include?(name)} ||
      request.referrer.blank?
  end

  # たぶんもういらない
  def redirect_to(url)
    return super unless ps3?
    # PS3 でふつうにリダイレクトすると bad content body と言われる
    # meta refresh だとリファラーが付かず、画像だけ表示になってしまうのでトップへ
    @url = root_url
    render inline: <<-XXX.strip_heredoc
      <%= tag(:meta,
              'http-equiv'=>'refresh',
              content: '0;%s' % @url) %>
    XXX
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entries.html.erb
<%= paginate entries %>
<%= section class: "entries autopagerize_page_element" do %>
<% entries.each do |entry| %>
 <%= render entry %>
<% end %>
<% end %>
<%= paginate entries %>

app/views/entries/_entry.html.erb
<%= article({
      class: entry.idol.try(:romaji),
    }) do %>
 <% if entry.photo.present? %>
 <p class="thumbnail">
  <%= link_to(
        lazy_image(entry.photo.url(:thumb), alt: entry.id),
        entry) %>
 </p>
 <% end %>
 <div class="text">
  <p class="body">
   <%= entry.body %>
  </p>
  <%= footer do %>
   <% if entry.root? %>
    <span class="tags">
     <% entry.tags.each do |tag| %>
      <%= link_to(tag.name, tag) %>
     <% end %>
    </span>
   <% end %>
   <%= entry_time(entry) %>
  <% end %>
 </div>
<% end %>

app/views/entries/_form.html.erb
<%# -*- encoding: UTF-8 -*-%>
<% @entry ||= Entry.new %>
<%= form_for @entry, multipart: true do |f| %>
 <%= render 'shared/error_messages', target: @entry %>
 <table>
  <tr>
   <th>ファイル</th>
   <td><%= f.file_field :photo, size: 40 %></td>
  </tr>
  <tr>
   <th>コメント</th>
   <td><%= f.text_area :body, size: '40x2' %></td>
  </tr>
  <tr>
   <th>タグ</th>
   <td>
    <p>省略時はファイル名（千早_1.jpg 等）から自動で設定します</p>
    <%= render 'form_tags', entry: @entry, f: f %>
   </td>
  </tr>
 </table>
 <p class="buttons"><%= f.submit '送信' %></p>
<% end %>

app/views/entries/_form_tags.html.erb
<% idol_names.each_with_index do |name, i| %>
 <%- id = 'tag%d' % i -%>
 <%= check_box_tag 'entry[tag_list][]', name, entry.tag_list.include?(name), id: id
  %><%= label_tag id, name %>
<% end %>
|
その他 (スペース区切り)
 <%= f.text_field :other_tags, size: 20 %>

app/views/entries/_replies.html.erb
<%= section class: "replies" do %>
 <% replies.reverse.each do |reply| %>

<%= article(id: 'reply-%d' % reply.id) do %>
 <% if reply.photo.present? %>
 <p class="thumbnail">
  <%= link_to(
        image_tag(reply.photo.url(:thumb), alt: reply.id, rel: 'photo'),
        reply.photo.url) %>
 </p>
 <% end %>
 <p class="body"><%= reply.body %></p>
 <%= footer do %>
  <%= link_to(entry_time(reply), reply) %>
 <% end %>
<% end %>

 <% end %>
 <%= paginate replies %>
<% end %>

app/views/entries/_tags.html.erb
<section id="tags">
 <h1><%= t('tags') %></h1>
<%= nav class: 'tag-cloud' do %>
<% Idol.all.each do |idol| %>
<%= link_to(idol.name, 
            acts_as_taggable_on_tag_path(idol.name),
            class: 'tag %s' % idol.romaji) %>
<% end %>
<%= link_to('あみまみ', 
            acts_as_taggable_on_tag_path('亜美 真美', any: 1),
            class: 'tag ami mami') %>
<% end %>
</section>

app/views/entries/edit.html.erb
<%# -*- encoding: UTF-8 -*-%>
<% content_for :head do %>
 <%= tag(:meta, name: 'robots', cntent: 'noindex') %>
<% end %>
<%= render @entry %>

<%= section do %>
 <h2>タグを編集</h2>
 <%= form_for @entry do |f| %>
  <table>
   <tr>
    <th>タグ</th>
    <td>
     <%= render 'form_tags', entry: @entry, f: f %>
    </td>
   </tr>
  </table>
  <p class="buttons"><%= f.submit '更新' %></p>
 <% end %>
<% end %>

app/views/entries/index.html.erb
<div id="form-container">
 <p><%= link_to('アップロードする', [:new, :entry], id: 'open-form', class: 'button') %></p>
 <%= render 'form' %>
</div>

<%= render 'tags', tags: @tags if @tags %>

<%= render 'entries/entries', entries: @entries %>

app/views/entries/new.html.erb
<% content_for :head do %>
 <%= tag(:meta, name: 'robots', cntent: 'noindex') %>
<% end %>
<section class="upload">
 <h2>ファイルをアップロードする</h2>
<%= render 'form' %>
</section>

app/views/entries/show.html.erb
<% content_for :head do %>
 <%= tag(:link, rel: 'canonical', href: entry_url(@entry)) %>
<% end %>
<%= article({
      class: @entry.idol.try(:romaji),
      id: "full",
    }) do %>
<p class="photo">
<%= link_to(
      image_tag(@entry.photo.url(:original), alt: @entry.id, rel: 'photo'),
      @entry.photo.url(:original)) %>
</p>
<p class="body"><%= @entry.body %></p>
<%= footer do %>
   <% if @entry.root? %>
    <span class="tags">
     <% @entry.tags.each do |tag| %>
      <%= link_to(tag.name, tag) %>
     <% end %>
    </span>
   <% end %>
   <%= link_to(entry_time(@entry), @entry) %>
<% end %>
<% end %>

<%= render 'shared/share' %>

<% if @entry.root? %>
 <p><%= link_to('タグを編集(仮)', [:edit, @entry]) %></p>
<% end %>

<%= render 'shared/affiliate' %>